import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import ProductInitializer from "@/components/home/ProductInitialiser";
import { Toaster } from "sonner";



const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata = {
  title: "Sree Priyaas Boutique",
  description: "Generated by Next.js",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body>
        {/* <ProductInitializer/> */}
        {children}
         <Toaster richColors position="top-right" />
        </body>
    </html>
  );
}