import './globals.css'

export const metadata = {
  title: 'Sree Priyaas Boutique',
   description: 'Generated by Next.js',
  icons: {
    icon: '/logo.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
